defaults:
  - model_vqvae_transformer_split
  - _self_

model_kwargs:
  split_quantizer_cfg:
    branch_order: ["mu", "alpha"]
    mu_quantizer: vq
    alpha_quantizer: fsq
    branch_loss_weights:
      mu: 0.25
      alpha: 1.0
    vq_mu_num_codes: 8
    fsq_alpha_levels: [64]
    vq_kwargs:
      rotation_tr: False
