defaults:
  - model_vqvae_transformer_split
  - _self_

model_kwargs:
  split_quantizer_cfg:
    branch_order: ["mu"]
    branch_loss_weights:
      mu: 5.0
      alpha: 5.0
    fsq_mu_levels: [25, 25, 25]
