_target_: gabbro.models.vqvae.FaissKMeansBaselineLightning
pid_cfg: ${pid}

num_codes: 512
fit_max_particles: 1000000
fit_max_batches: 1000
niter: 25
nredo: 1
seed: ${seed}
use_gpu: true

save_codebook: true
upload_codebook_to_wandb: true

max_validation_plot_batches: 0
max_test_plot_batches: null
