defaults:
  - model_summary.yaml
  - model_checkpoint.yaml
  - lr_monitor.yaml
  - orbit_plotting_callback.yaml
  - token_export_callback.yaml
  - gradient_monitoring.yaml
  - _self_

model_summary:
  max_depth: -1

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: best
  save_top_k: 1
  save_last: true
  auto_insert_metric_name: false

gradient_monitoring:
  logging_interval: 10
  depth: 0
  prefix: grad/global

gradient_monitoring_global:
  logging_interval: 50
  depth: 2
  prefix: grad/components
